### ISSUE TITLE
README figure is low-res and transparent

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/waveorder#106]
The latest README figure is lower resolution than the previous one, so the smallest text is barely legible:

<img width="556" alt="Screen Shot 2023-02-22 at 11 00 20 AM" src="https://user-images.githubusercontent.com/9554101/220732458-0c78f222-69ff-441d-9f72-290d413e5804.png">

@ziw-liu also pointed out that the background is mostly transparent and inconsistent:

> the equation in the figure is on a solid white background, while the rest of the figure is on a transparent background that may have contrast issues in a dark theme

@mattersoflight can you point me to the source file or fix these when you get a chance?

Note: this does not need to be fixed before the release, since I'm linking the github file directly (I learned through recOrder releases that linking the github file is a good strategy since distributing .pngs is suboptimal---no need to pip-install big pngs for everyone).

**Comment by mattersoflight** [comment]
Sorry for the delay @talonchandler- [here](https://drive.google.com/open?id=16RWCXHDX0z-C_HWlmHsxtkquY5WNfznb&usp=drive_fs) the source PDF on our google drive. The folder `Figure_Apr2022` has all the other figures too.

@ziw-liu pointed me to the [trick](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) to show different images when the github theme changes, which I think is the way to go for all READMEs.

**Comment by ziw-liu** [comment]
> the [trick](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) to show different images when the github theme changes

Example in viscy: https://github.com/mehta-lab/viscy/pull/22#discussion_r1273912193
