### ISSUE TITLE
`opencv-python` is taking >30 minutes to build on M1

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/waveorder#107]
`opencv-python` just released version `4.7.0.72` and it is taking >30 minutes to build on my M1. Installing the same version on Windows is fast, and installing the earlier version `4.7.0.68` is also fast. 

@ziw-liu I'm considering pinning `opencv-python==4.7.0.68` for this release, so that I can move forward. As [you mention](https://github.com/mehta-lab/waveorder/issues/97#issuecomment-1423089852), we not depending on opencv very much and it may be causing a bug so we're planning to remove this dependency soon anyway. 

@ziw-liu are you able to replicate an extremely slow `opencv-python` build? This problem affects `recOrder` installations on my M1 too.

**Comment by talonchandler** [comment]
Actually...just pinning and releasing in `waveorder` doesn't fix the issue since existing versions of `recOrder` will install `opencv` too. We may need to consider pinning the version in `recOrder` too.

**Comment by ziw-liu** [comment]
> We may need to consider pinning the version in `recOrder` too.

`RecOrder` at the main branch does not depend on OpenCV anymore (https://github.com/mehta-lab/recOrder/commit/e68aaaba46383a0a2aed6a87a20dad1099487ddd). Since `recOrder` 0.2.x pins waveorder to 1.0.0rc0 anyway and 0.3.0 will be released without the OpenCV dependency, I guess this is not a big issue?

**Comment by ziw-liu** [comment]
That being said, I think we should remove OpenCV for waveorder too. The only function that uses it is not used, not tested, and confusingly written. I can make a quick fix or removal if that sounds good.

**Comment by talonchandler** [comment]
Okay great, thanks Ziwen. I'll go ahead and upload the release, since this is at worst an inconvenience.
