### ISSUE TITLE
Removing I/O module

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/waveorder#112]
Moving the conversation over from https://github.com/czbiohub/iohub/issues/55#issuecomment-1483121289:

> Remove WaveorderReader from waveorder and depend on the tagged version of iohub via github. After testing, release waveorder==1.0.0.

@talonchandler Does waveorder need to depend on iohub? I thought the plan was to turn waveorder into an array-in-array-out library and leave file I/O to downstream applications like recOrder.

**Comment by ziw-liu** [comment]
I'm not too worried about not specifying the dependency for examples in the package setup. We are not doing it now: jupyter is not a dependency, and many examples are notebooks. Optional `[examples]` requirement or a line in the example's README file should be enough.

**Comment by talonchandler** [comment]
Okay sounds good, I'm happy with dropping the explicit `iohub` dependency in `waveorder` and having both an `[examples]` requirement and a line in `examples/README.md`. 

`napari` and `matplotlib` might also live in the `[examples]` requirements.

**Comment by ziw-liu** [comment]
> `napari` and `matplotlib` might also live in the `[examples]` requirements.

Matplotlib is used in the visual module though.

**Comment by talonchandler** [comment]
Closing this. I/O has been completely removed from `waveorder`, and (opposite of what I though above) none of the examples need to depend on `iohub`. 

The small of amount of io is via `.npz` files and matplotlib.
