### ISSUE TITLE
Make `torch` optional dependency?

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/waveorder#130]
Does it make sense to make `torch` an optional dependency? How easy it it to write non-`torch` accelerated versions of the `waveorder` algorithms? Are there cases where we'd like to use `waveorder` but cannon install `torch`, e.g. no GPU?

**Comment by mattersoflight** [comment]
`torch` is a generic replacement for `numpy` on CPU, GPU, or integrated chips like M1.

**Comment by talonchandler** [comment]
@ieivanov what's the motivation here? Have you run into issues using/installing torch? 

So far I haven't had any trouble with `pip install torch` on machines with or without gpus.

**Comment by ieivanov** [comment]
No issues, just asking for now. I'll try installing `torch` on mantis and I'll let you know if I run into any problems.

**Comment by ieivanov** [comment]
No issues installing `torch` on mantis
