### ISSUE TITLE
Interface of WaveorderWriter.writer is not "pythonic"

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/waveorder#47]
The t, c, z input interface to WaveorderWriter.writer is not very pythonic. It makes sense for these parameters to be integers or iterables (e.g. `c = range(4)`) as opposed to list of start and end indices, i.e. `c = [0, 4]`. This should simplify WriterBase.write too

**Comment by camFoltz** [comment]
Good idea, I'll make these changes.  You're right in that it will simplify the code

**Comment by ieivanov** [comment]
I did some looking to that after I first created the issue, we should use `slice` rather than `range`, take a look here: https://zarr.readthedocs.io/en/stable/api/core.html#zarr.core.Array.get_basic_selection. The difference is subtle, I think.

**Comment by camFoltz** [comment]
fixed in #60
