### ISSUE TITLE
WaveroderReader should set ome-zarr metadata color to FFFFFF

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/waveorder#50]
FFFFFF corresponds to "gray" colormap

**Comment by ieivanov** [comment]
napari still calles this colormap "unnamed" and creates a whole bunch such colormaps for every channel loaded. I think this is a bug with the napari-ome-zarr plugin, we should create an issue there

**Comment by camFoltz** [comment]
fixed in #60 and also opened up issue in napari-ome-zarr
