### ISSUE TITLE
WaveorderReader should set only the first channel as active on ome-zarr metadata

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/waveorder#51]
This way when loaded in napari other channels are not visible and data are not overlayed. Overlaying usually does not make sense for our data

**Comment by camFoltz** [comment]
That is an easy change -- I think that this should live in the writer and not necessary on the reader level however.  We open the zarr store in a read-only mode so it is not possible to edit the metadata and I think it is safer that way.  I can implement this change in the writer.

**Comment by camFoltz** [comment]
fixed in #60
