### ISSUE TITLE
WaveorderReader should try to guess data_type and make that an optional argument

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/waveorder#53]

**Comment by camFoltz** [comment]
Yeah I have had this idea for a while, it will be easy enough to do this for OME-zarr datasets (quick metadata check + looking for the `.zarr` ending.  

Multipage vs. single-page tiff may have some easily accessible information in the header to distinguish, but if not we could just look to see if the file contains multiple pages, or not.  This latter strategy might mess with how we read the metadata however, as one can technically save a single snapshot as multi-page tiff (metadata embedded in the file) versus single snapshot as single-page tiff (metadata exists in external file).  I'll look into this a bit but I do not think it would be difficult to implement.

**Comment by ieivanov** [comment]
That would be great, thanks. I think a defining feature of zarr datasets is the `.zgroup` file, not so much the `.zarr` extension, I've run into problems with forgetting to add .`zarr` to the dataset name before.

I believe Bryant did some work to properly parse tif files, but I'm not sure where that lives

**Comment by camFoltz** [comment]
fixed in #60
