### ISSUE TITLE
WaveorderWriter default array name

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/waveorder#57]
Zarr defaults to calling an unnamed array `arr_0`, maybe we can call the array that the WaveorderWriter writes `arr_0` instead of `array`. This way we can use the dot notation to index the array: zs.arr_0 instead of zs['arr_0']. @camFoltz if you remember zs.array is a method that we're overloading by calling the data array `array`

**Comment by camFoltz** [comment]
Ah yes, I am perfectly happy with that nomenclature.  I can make this change with the others.

**Comment by camFoltz** [comment]
fixed in #60
